// Temporary handwritten types for Phase 2. Replace with `supabase gen types typescript`
// after a Supabase project is connected. Keep this shape aligned with the migration.
export type Database = {
  public: {
    Tables: {
      profiles: { Row: { id: string; display_name: string; role: "member" | "admin"; member_slot: number; created_at: string; updated_at: string }; Insert: Omit<Database["public"]["Tables"]["profiles"]["Row"], "created_at" | "updated_at"> & Partial<Pick<Database["public"]["Tables"]["profiles"]["Row"], "created_at" | "updated_at">>; Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]> };
      kitchen_templates: { Row: { id: string; effective_from: string; created_at: string; updated_at: string }; Insert: Omit<Database["public"]["Tables"]["kitchen_templates"]["Row"], "id" | "created_at" | "updated_at"> & Partial<Pick<Database["public"]["Tables"]["kitchen_templates"]["Row"], "id" | "created_at" | "updated_at">>; Update: Partial<Database["public"]["Tables"]["kitchen_templates"]["Insert"]> };
      kitchen_template_slots: { Row: { id: string; template_id: string; weekday: number; duty_type: "cook" | "dishes"; slot_number: number; assigned_to: string }; Insert: Omit<Database["public"]["Tables"]["kitchen_template_slots"]["Row"], "id"> & Partial<Pick<Database["public"]["Tables"]["kitchen_template_slots"]["Row"], "id">>; Update: Partial<Database["public"]["Tables"]["kitchen_template_slots"]["Insert"]> };
      kitchen_duties: { Row: { id: string; date: string; duty_type: "cook" | "dishes"; slot_number: number; assigned_to: string; delegated_to: string | null; completed_by: string | null; status: "unconfirmed" | "completed"; completed_at: string | null; created_at: string; updated_at: string }; Insert: Omit<Database["public"]["Tables"]["kitchen_duties"]["Row"], "id" | "created_at" | "updated_at"> & Partial<Pick<Database["public"]["Tables"]["kitchen_duties"]["Row"], "id" | "created_at" | "updated_at">>; Update: Partial<Database["public"]["Tables"]["kitchen_duties"]["Insert"]> };
      dinner_plans: { Row: { member_id: string; date: string; plan: "eating" | "not_eating"; created_at: string; updated_at: string }; Insert: Omit<Database["public"]["Tables"]["dinner_plans"]["Row"], "created_at" | "updated_at"> & Partial<Pick<Database["public"]["Tables"]["dinner_plans"]["Row"], "created_at" | "updated_at">>; Update: Partial<Database["public"]["Tables"]["dinner_plans"]["Insert"]> };
      dinner_checkins: { Row: { member_id: string; date: string; completed_at: string; created_at: string }; Insert: Omit<Database["public"]["Tables"]["dinner_checkins"]["Row"], "created_at" | "completed_at"> & Partial<Pick<Database["public"]["Tables"]["dinner_checkins"]["Row"], "created_at" | "completed_at">>; Update: Partial<Database["public"]["Tables"]["dinner_checkins"]["Insert"]> };
      housework_rotations: { Row: { id: string; effective_from: string; created_at: string; updated_at: string }; Insert: Omit<Database["public"]["Tables"]["housework_rotations"]["Row"], "id" | "created_at" | "updated_at"> & Partial<Pick<Database["public"]["Tables"]["housework_rotations"]["Row"], "id" | "created_at" | "updated_at">>; Update: Partial<Database["public"]["Tables"]["housework_rotations"]["Insert"]> };
      housework_rotation_members: { Row: { rotation_id: string; position: number; member_id: string }; Insert: Database["public"]["Tables"]["housework_rotation_members"]["Row"]; Update: Partial<Database["public"]["Tables"]["housework_rotation_members"]["Insert"]> };
      housework_weeks: { Row: { id: string; week_start: string; responsible_member_id: string; created_at: string; updated_at: string }; Insert: Omit<Database["public"]["Tables"]["housework_weeks"]["Row"], "id" | "created_at" | "updated_at"> & Partial<Pick<Database["public"]["Tables"]["housework_weeks"]["Row"], "id" | "created_at" | "updated_at">>; Update: Partial<Database["public"]["Tables"]["housework_weeks"]["Insert"]> };
      housework_checkins: { Row: { id: string; member_id: string; date: string; week_start: string; completed_at: string; created_at: string }; Insert: Omit<Database["public"]["Tables"]["housework_checkins"]["Row"], "id" | "created_at" | "completed_at" | "week_start"> & Partial<Pick<Database["public"]["Tables"]["housework_checkins"]["Row"], "id" | "created_at" | "completed_at">>; Update: Partial<Database["public"]["Tables"]["housework_checkins"]["Insert"]> };
      food_households: { Row: { id: string; name: string; rotation_position: number; is_enabled: boolean; created_at: string; updated_at: string }; Insert: Omit<Database["public"]["Tables"]["food_households"]["Row"], "id" | "created_at" | "updated_at"> & Partial<Pick<Database["public"]["Tables"]["food_households"]["Row"], "id" | "created_at" | "updated_at">>; Update: Partial<Database["public"]["Tables"]["food_households"]["Insert"]> };
      food_batches: { Row: { id: string; household_id: string; previous_batch_id: string | null; status: "waiting" | "active" | "finished"; start_date: string | null; finished_at: string | null; note: string | null; created_at: string; updated_at: string }; Insert: Omit<Database["public"]["Tables"]["food_batches"]["Row"], "id" | "created_at" | "updated_at"> & Partial<Pick<Database["public"]["Tables"]["food_batches"]["Row"], "id" | "created_at" | "updated_at">>; Update: Partial<Database["public"]["Tables"]["food_batches"]["Insert"]> };
    };
    Views: Record<string, never>;
    Functions: { is_family_member: { Args: Record<string, never>; Returns: boolean }; is_family_admin: { Args: Record<string, never>; Returns: boolean } };
    Enums: { profile_role: "member" | "admin"; kitchen_duty_type: "cook" | "dishes"; kitchen_duty_status: "unconfirmed" | "completed"; dinner_plan: "eating" | "not_eating"; food_batch_status: "waiting" | "active" | "finished" };
    CompositeTypes: Record<string, never>;
  };
};
